import { appSchema, tableSchema } from '@nozbe/watermelondb'

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'profiles',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'full_name', type: 'string' },
        { name: 'email', type: 'string' },
        { name: 'role', type: 'string' },
        { name: 'created_at', type: 'string', isOptional: true },
        { name: 'updated_at', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'projects',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'client_name', type: 'string' },
        { name: 'location', type: 'string', isOptional: true },
        { name: 'budget', type: 'number', isOptional: true },
        { name: 'start_date', type: 'string', isOptional: true },
        { name: 'due_date', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'priority', type: 'string' },
        { name: 'phase', type: 'string' },
        { name: 'planning_category', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string' },
        { name: 'created_at', type: 'string', isOptional: true },
        { name: 'updated_at', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'project_members',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'project_id', type: 'string' },
        { name: 'user_id', type: 'string' },
        { name: 'access_role', type: 'string' },
        { name: 'created_at', type: 'string', isOptional: true },
        { name: 'updated_at', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'tasks',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'project_id', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'priority', type: 'string' },
        { name: 'due_date', type: 'string', isOptional: true },
        { name: 'assigned_to', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string' },
        { name: 'created_at', type: 'string', isOptional: true },
        { name: 'updated_at', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'follow_ups',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'project_id', type: 'string' },
        { name: 'task_id', type: 'string', isOptional: true },
        { name: 'note', type: 'string' },
        { name: 'next_follow_up_date', type: 'string', isOptional: true },
        { name: 'responsible_user_id', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'created_by', type: 'string' },
        { name: 'created_at', type: 'string', isOptional: true },
        { name: 'updated_at', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'reminders',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string' },
        { name: 'project_id', type: 'string', isOptional: true },
        { name: 'task_id', type: 'string', isOptional: true },
        { name: 'remind_at', type: 'string' },
        { name: 'message', type: 'string' },
        { name: 'is_done', type: 'boolean' },
        { name: 'created_at', type: 'string', isOptional: true },
        { name: 'updated_at', type: 'string', isOptional: true },
      ],
    }),
  ],
})
